#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : curl
Version  : 7.51.0
Release  : 50
URL      : https://curl.haxx.se/download/curl-7.51.0.tar.gz
Source0  : https://curl.haxx.se/download/curl-7.51.0.tar.gz
Summary  : Library to transfer files with ftp, http, etc.
Group    : Development/Tools
License  : ICU MIT OpenSSL
Requires: curl-bin
Requires: curl-lib
Requires: curl-doc
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : ca-certs
BuildRequires : cmake
BuildRequires : dbus-dev
BuildRequires : gettext-bin
BuildRequires : groff
BuildRequires : libidn-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config-dev
BuildRequires : python-dev
BuildRequires : zlib-dev
Patch1: nodes.patch
Patch2: 0001-stateless-plus.patch
Patch3: Add-pacrunner-call-for-autoproxy-resolution.patch
Patch4: Check-pacdiscovery-state-file-exists.patch

%description
_   _ ____  _
___| | | |  _ \| |
/ __| | | | |_) | |
| (__| |_| |  _ <| |___
\___|\___/|_| \_\_____|

%package bin
Summary: bin components for the curl package.
Group: Binaries

%description bin
bin components for the curl package.


%package dev
Summary: dev components for the curl package.
Group: Development
Requires: curl-lib
Requires: curl-bin
Provides: curl-devel

%description dev
dev components for the curl package.


%package doc
Summary: doc components for the curl package.
Group: Documentation

%description doc
doc components for the curl package.


%package lib
Summary: lib components for the curl package.
Group: Libraries

%description lib
lib components for the curl package.


%prep
%setup -q -n curl-7.51.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export LANG=C
%reconfigure --disable-static --with-openssl \
--disable-ldap \
--without-winidn \
--with-libidn \
--enable-threaded-resolver \
--disable-ipv6 \
--with-zlib \
--enable-symbol-hiding \
--with-ca-path=%{_datadir}/ca-certs \
--with-ca-bundle=%{_sysconfdir}/ssl/cert.pem \
--without-ntlm \
--disable-ntlm-wb \
--disable-ntlm \
--disable-smb \
--enable-proxy \
--with-nghttp2 \
--enable-ipv6
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/curl
/usr/bin/curl-config

%files dev
%defattr(-,root,root,-)
/usr/include/curl/curl.h
/usr/include/curl/curlbuild.h
/usr/include/curl/curlrules.h
/usr/include/curl/curlver.h
/usr/include/curl/easy.h
/usr/include/curl/mprintf.h
/usr/include/curl/multi.h
/usr/include/curl/stdcheaders.h
/usr/include/curl/typecheck-gcc.h
/usr/lib64/libcurl.so
/usr/lib64/pkgconfig/libcurl.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcurl.so.4
/usr/lib64/libcurl.so.4.4.0
