#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : curl
Version  : 7.78.0
Release  : 403
URL      : file:///aot/build/clearlinux/packages/curl/curl-v7.78.0.tar.gz
Source0  : file:///aot/build/clearlinux/packages/curl/curl-v7.78.0.tar.gz
Summary  : Library to transfer files with ftp, http, etc.
Group    : Development/Tools
License  : MIT
Requires: curl-bin = %{version}-%{release}
Requires: curl-lib = %{version}-%{release}
Requires: curl-man = %{version}-%{release}
Requires: ca-certs
BuildRequires : CUnit-dev
BuildRequires : CUnit-staticdev
BuildRequires : Cython
BuildRequires : Flask
BuildRequires : Sphinx
BuildRequires : acl-dev
BuildRequires : acl-staticdev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : boost-dev
BuildRequires : brotli-dev
BuildRequires : brotli-dev32
BuildRequires : brotli-staticdev
BuildRequires : brotli-staticdev32
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : c-ares
BuildRequires : c-ares-dev
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : check-dev
BuildRequires : curl-dev
BuildRequires : cyrus-sasl-dev
BuildRequires : dbus
BuildRequires : dbus-broker
BuildRequires : dbus-dev
BuildRequires : dbus-dev32
BuildRequires : dbus-extras
BuildRequires : dbus-glib
BuildRequires : dbus-glib-dev
BuildRequires : dbus-python
BuildRequires : dejagnu
BuildRequires : desktop-file-utils
BuildRequires : diffstat
BuildRequires : diffutils
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : e2fsprogs-data
BuildRequires : e2fsprogs-dev
BuildRequires : e2fsprogs-dev32
BuildRequires : e2fsprogs-extras
BuildRequires : e2fsprogs-staticdev
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : expect
BuildRequires : extra-cmake-modules
BuildRequires : file-dev
BuildRequires : findutils
BuildRequires : flex
BuildRequires : gcc
BuildRequires : gcc-abi
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-doc
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gengetopt
BuildRequires : gettext-bin
BuildRequires : gettext-dev
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glibc-staticdev
BuildRequires : gnupg
BuildRequires : gperf
BuildRequires : gpgme
BuildRequires : gpgme-dev
BuildRequires : groff
BuildRequires : groff-bin
BuildRequires : gssapi
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : json-c
BuildRequires : json-c-dev
BuildRequires : json-c-staticdev
BuildRequires : keyutils-dev
BuildRequires : keyutils-staticdev
BuildRequires : krb5-bin
BuildRequires : krb5-data
BuildRequires : krb5-dev
BuildRequires : krb5-lib
BuildRequires : krb5-staticdev
BuildRequires : libassuan-dev
BuildRequires : libc6
BuildRequires : libcomps-dev
BuildRequires : libdnf-dev
BuildRequires : libev-dev
BuildRequires : libevent
BuildRequires : libevent-dev
BuildRequires : libevent-dev32
BuildRequires : libgcc1
BuildRequires : libgcrypt
BuildRequires : libgcrypt-dev
BuildRequires : libidn-dev
BuildRequires : libidn-dev32
BuildRequires : libidn2-dev
BuildRequires : libidn2-dev32
BuildRequires : libidn2-staticdev
BuildRequires : libidn2-staticdev32
BuildRequires : libmodulemd
BuildRequires : libmodulemd-dev
BuildRequires : librepo-dev
BuildRequires : libsolv-dev
BuildRequires : libstdc++
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libunistring-dev
BuildRequires : libunistring-dev32
BuildRequires : libunistring-staticdev
BuildRequires : libunistring-staticdev32
BuildRequires : libxml2
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32
BuildRequires : libxml2-staticdev
BuildRequires : libxslt-bin
BuildRequires : libxslt-dev
BuildRequires : libxslt-staticdev
BuildRequires : lmdb-dev
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : m4
BuildRequires : nettle-dev
BuildRequires : nghttp2-dev
BuildRequires : nghttp2-dev32
BuildRequires : nghttp2-staticdev
BuildRequires : nose
BuildRequires : openldap-dev
BuildRequires : openssl-dev
BuildRequires : openssl-dev32
BuildRequires : openssl-staticdev
BuildRequires : perl
BuildRequires : perl-Acme-Damn
BuildRequires : perl-Algorithm-C3
BuildRequires : perl-Algorithm-Combinatorics
BuildRequires : perl-Algorithm-Diff
BuildRequires : perl-Algorithm-Diff-XS
BuildRequires : perl-Algorithm-Merge
BuildRequires : perl-Algorithm-Munkres
BuildRequires : perl-Alien-Build
BuildRequires : perl-Alien-Libxml2
BuildRequires : perl-Alien-m4
BuildRequires : perl-AnyEvent
BuildRequires : perl-AnyEvent-AIO
BuildRequires : perl-AnyEvent-BDB
BuildRequires : perl-AnyEvent-CacheDNS
BuildRequires : perl-Apache-Htpasswd
BuildRequires : perl-Apache-LogFormat-Compiler
BuildRequires : perl-Apache-Session
BuildRequires : perl-App-MigrateModules
BuildRequires : perl-App-Nopaste
BuildRequires : perl-App-cpanminus
BuildRequires : perl-App-perlbrew
BuildRequires : perl-AppConfig
BuildRequires : perl-Archive-Cpio
BuildRequires : perl-Archive-Extract
BuildRequires : perl-Archive-Tar-Wrapper
BuildRequires : perl-Array-Unique
BuildRequires : perl-Array-Utils
BuildRequires : perl-Async-Interrupt
BuildRequires : perl-Async-MergePoint
BuildRequires : perl-Audio-FLAC-Header
BuildRequires : perl-Audio-Musepack
BuildRequires : perl-Audio-Scan
BuildRequires : perl-Audio-Wav
BuildRequires : perl-Authen-NTLM
BuildRequires : perl-Authen-SASL
BuildRequires : perl-B-COW
BuildRequires : perl-B-Debug
BuildRequires : perl-B-Hooks-EndOfScope
BuildRequires : perl-B-Hooks-OP-Check
BuildRequires : perl-B-Keywords
BuildRequires : perl-BDB
BuildRequires : perl-BSD-Resource
BuildRequires : perl-Bencode
BuildRequires : perl-Biblio-EndnoteStyle
BuildRequires : perl-Bit-Vector
BuildRequires : perl-Browser-Open
BuildRequires : perl-Business-ISBN
BuildRequires : perl-Business-ISBN-Data
BuildRequires : perl-Business-ISMN
BuildRequires : perl-Business-ISSN
BuildRequires : perl-CBOR-XS
BuildRequires : perl-CDDB-File
BuildRequires : perl-CGI
BuildRequires : perl-CGI-Compile
BuildRequires : perl-CGI-Emulate-PSGI
BuildRequires : perl-CGI-Simple
BuildRequires : perl-CPAN-Changes
BuildRequires : perl-CPAN-DistnameInfo
BuildRequires : perl-CPAN-Meta-Check
BuildRequires : perl-CPAN-Perl-Releases
BuildRequires : perl-CSS-DOM
BuildRequires : perl-CSS-Minifier-XS
BuildRequires : perl-CSS-Tiny
BuildRequires : perl-Cache-Simple-TimedExpiry
BuildRequires : perl-Calendar-Simple
BuildRequires : perl-Canary-Stability
BuildRequires : perl-Capture-Tiny
BuildRequires : perl-Carp-Always
BuildRequires : perl-Carp-Assert
BuildRequires : perl-Carp-Assert-More
BuildRequires : perl-Carp-Clan
BuildRequires : perl-Class-Accessor
BuildRequires : perl-Class-Accessor-Chained
BuildRequires : perl-Class-Accessor-Grouped
BuildRequires : perl-Class-Accessor-Lite
BuildRequires : perl-Class-Base
BuildRequires : perl-Class-C3
BuildRequires : perl-Class-C3-Componentised
BuildRequires : perl-Class-Container
BuildRequires : perl-Class-Data-Accessor
BuildRequires : perl-Class-Data-Inheritable
BuildRequires : perl-Class-ErrorHandler
BuildRequires : perl-Class-Factory-Util
BuildRequires : perl-Class-ISA
BuildRequires : perl-Class-Inspector
BuildRequires : perl-Class-Load
BuildRequires : perl-Class-Load-XS
BuildRequires : perl-Class-Measure
BuildRequires : perl-Class-Method-Modifiers
BuildRequires : perl-Class-MethodMaker
BuildRequires : perl-Class-Mix
BuildRequires : perl-Class-Refresh
BuildRequires : perl-Class-ReturnValue
BuildRequires : perl-Class-Singleton
BuildRequires : perl-Class-Std
BuildRequires : perl-Class-Std-Fast
BuildRequires : perl-Class-Tiny
BuildRequires : perl-Class-Trigger
BuildRequires : perl-Class-Unload
BuildRequires : perl-Class-XSAccessor
BuildRequires : perl-Clipboard
BuildRequires : perl-Clone
BuildRequires : perl-Clone-Choose
BuildRequires : perl-Clone-PP
BuildRequires : perl-Compress-Bzip2
BuildRequires : perl-Compress-Raw-Lzma
BuildRequires : perl-Config-Any
BuildRequires : perl-Config-AutoConf
BuildRequires : perl-Config-General
BuildRequires : perl-Config-Grammar
BuildRequires : perl-Config-INI
BuildRequires : perl-Config-INI-Reader-Ordered
BuildRequires : perl-Config-IniFiles
BuildRequires : perl-Config-Std
BuildRequires : perl-Config-Tiny
BuildRequires : perl-Const-Fast
BuildRequires : perl-Context-Preserve
BuildRequires : perl-Contextual-Return
BuildRequires : perl-Convert-ASN1
BuildRequires : perl-Convert-Bencode
BuildRequires : perl-Convert-Bencode_XS
BuildRequires : perl-Convert-Binary-C
BuildRequires : perl-Cookie-Baker
BuildRequires : perl-Coro
BuildRequires : perl-Cpanel-JSON-XS
BuildRequires : perl-Crypt-DH-GMP
BuildRequires : perl-Crypt-Eksblowfish
BuildRequires : perl-Crypt-GeneratePassword
BuildRequires : perl-Crypt-Random-Seed
BuildRequires : perl-Crypt-Rijndael
BuildRequires : perl-Crypt-SSLeay
BuildRequires : perl-Crypt-URandom
BuildRequires : perl-Curses
BuildRequires : perl-DBD-Pg
BuildRequires : perl-DBD-SQLite
BuildRequires : perl-DBD-SQLite2
BuildRequires : perl-DBD-mysql
BuildRequires : perl-DBI
BuildRequires : perl-DBICx-TestDatabase
BuildRequires : perl-DBIx-Class
BuildRequires : perl-DBIx-Class-DeploymentHandler
BuildRequires : perl-DBIx-Class-DynamicDefault
BuildRequires : perl-DBIx-Class-OptimisticLocking
BuildRequires : perl-DBIx-Class-Schema-Config
BuildRequires : perl-DBIx-Connector
BuildRequires : perl-DBIx-ContextualFetch
BuildRequires : perl-DBIx-DBSchema
BuildRequires : perl-DBIx-Simple
BuildRequires : perl-DB_File
BuildRequires : perl-Data-Compare
BuildRequires : perl-Data-Denter
BuildRequires : perl-Data-Dump
BuildRequires : perl-Data-Dumper-Concise
BuildRequires : perl-Data-Dumper-Simple
BuildRequires : perl-Data-Float
BuildRequires : perl-Data-Flow
BuildRequires : perl-Data-Integer
BuildRequires : perl-Data-Munge
BuildRequires : perl-Data-OptList
BuildRequires : perl-Data-Page
BuildRequires : perl-Data-Password
BuildRequires : perl-Data-Printer
BuildRequires : perl-Data-Random
BuildRequires : perl-Data-Section
BuildRequires : perl-Data-Serializer
BuildRequires : perl-Data-Structure-Util
BuildRequires : perl-Data-Taxi
BuildRequires : perl-Data-Uniqid
BuildRequires : perl-Data-Validate-IP
BuildRequires : perl-Date-Manip
BuildRequires : perl-DateTime
BuildRequires : perl-DateTime-Format-Builder
BuildRequires : perl-DateTime-Format-DateParse
BuildRequires : perl-DateTime-Format-Flexible
BuildRequires : perl-DateTime-Format-ISO8601
BuildRequires : perl-DateTime-Format-Mail
BuildRequires : perl-DateTime-Format-MySQL
BuildRequires : perl-DateTime-Format-Natural
BuildRequires : perl-DateTime-Format-Pg
BuildRequires : perl-DateTime-Format-Strptime
BuildRequires : perl-DateTime-Format-W3CDTF
BuildRequires : perl-DateTime-Locale
BuildRequires : perl-DateTime-TimeZone
BuildRequires : perl-Debug-ShowStuff
BuildRequires : perl-Devel-ArgNames
BuildRequires : perl-Devel-CallChecker
BuildRequires : perl-Devel-Caller
BuildRequires : perl-Devel-CheckBin
BuildRequires : perl-Devel-CheckLib
BuildRequires : perl-Devel-CheckOS
BuildRequires : perl-Devel-Confess
BuildRequires : perl-Devel-Cover
BuildRequires : perl-Devel-Cycle
BuildRequires : perl-Devel-EnforceEncapsulation
BuildRequires : perl-Devel-GlobalDestruction
BuildRequires : perl-Devel-Hide
BuildRequires : perl-Devel-LexAlias
BuildRequires : perl-Devel-OverloadInfo
BuildRequires : perl-Devel-OverrideGlobalRequire
BuildRequires : perl-Devel-PatchPerl
BuildRequires : perl-Devel-Refactor
BuildRequires : perl-Devel-Size
BuildRequires : perl-Devel-StackTrace
BuildRequires : perl-Devel-StackTrace-AsHTML
BuildRequires : perl-Devel-Symdump
BuildRequires : perl-Digest-CRC
BuildRequires : perl-Digest-HMAC
BuildRequires : perl-Digest-JHash
BuildRequires : perl-Digest-MD5
BuildRequires : perl-Digest-SHA1
BuildRequires : perl-Digest-SHA3
BuildRequires : perl-Dist-CheckConflicts
BuildRequires : perl-Domain-PublicSuffix
BuildRequires : perl-Dumbbench
BuildRequires : perl-DynaLoader-Functions
BuildRequires : perl-EV
BuildRequires : perl-Email-Abstract
BuildRequires : perl-Email-Address
BuildRequires : perl-Email-Address-XS
BuildRequires : perl-Email-Date
BuildRequires : perl-Email-Date-Format
BuildRequires : perl-Email-MIME-Encodings
BuildRequires : perl-Email-MessageID
BuildRequires : perl-Email-Simple
BuildRequires : perl-Encode-HanExtra
BuildRequires : perl-Encode-JIS2K
BuildRequires : perl-Encode-Locale
BuildRequires : perl-Error
BuildRequires : perl-Eval-Closure
BuildRequires : perl-Exception-Class
BuildRequires : perl-Exporter-Declare
BuildRequires : perl-Exporter-Easy
BuildRequires : perl-Exporter-Lite
BuildRequires : perl-Exporter-Tidy
BuildRequires : perl-Exporter-Tiny
BuildRequires : perl-ExtUtils-Config
BuildRequires : perl-ExtUtils-Depends
BuildRequires : perl-ExtUtils-Helpers
BuildRequires : perl-ExtUtils-InstallPaths
BuildRequires : perl-ExtUtils-PkgConfig
BuildRequires : perl-FCGI-ProcManager
BuildRequires : perl-FFI-CheckLib
BuildRequires : perl-Feed-Find
BuildRequires : perl-Fennec-Lite
BuildRequires : perl-File-BaseDir
BuildRequires : perl-File-Copy-Link
BuildRequires : perl-File-Copy-Recursive
BuildRequires : perl-File-DesktopEntry
BuildRequires : perl-File-FcntlLock
BuildRequires : perl-File-Find-Rule
BuildRequires : perl-File-Grep
BuildRequires : perl-File-HomeDir
BuildRequires : perl-File-KeePass
BuildRequires : perl-File-LibMagic
BuildRequires : perl-File-Listing
BuildRequires : perl-File-MMagic
BuildRequires : perl-File-Modified
BuildRequires : perl-File-NCopy
BuildRequires : perl-File-Next
BuildRequires : perl-File-Path-Expand
BuildRequires : perl-File-Pid
BuildRequires : perl-File-ReadBackwards
BuildRequires : perl-File-Remove
BuildRequires : perl-File-ShareDir
BuildRequires : perl-File-ShareDir-Install
BuildRequires : perl-File-Slurp
BuildRequires : perl-File-Slurp-Tiny
BuildRequires : perl-File-Slurper
BuildRequires : perl-File-Sync
BuildRequires : perl-File-Tail
BuildRequires : perl-File-Touch
BuildRequires : perl-File-Type
BuildRequires : perl-File-Which
BuildRequires : perl-File-chdir
BuildRequires : perl-File-pushd
BuildRequires : perl-Filesys-Df
BuildRequires : perl-Filesys-Notify-Simple
BuildRequires : perl-Font-AFM
BuildRequires : perl-Font-TTF
BuildRequires : perl-FreezeThaw
BuildRequires : perl-Frontier-RPC
BuildRequires : perl-Future
BuildRequires : perl-Future-IO-ImplBase
BuildRequires : perl-GD
BuildRequires : perl-GD-Barcode
BuildRequires : perl-GIS-Distance
BuildRequires : perl-GSSAPI
BuildRequires : perl-Geo-Distance
BuildRequires : perl-Geo-IP
BuildRequires : perl-Geo-IPfree
BuildRequires : perl-Getopt-Euclid
BuildRequires : perl-Getopt-Long-Descriptive
BuildRequires : perl-Getopt-Long-Modern
BuildRequires : perl-Getopt-Tabular
BuildRequires : perl-Git-Version-Compare
BuildRequires : perl-Graph
BuildRequires : perl-Guard
BuildRequires : perl-HTML-Clean
BuildRequires : perl-HTML-Encoding
BuildRequires : perl-HTML-Form
BuildRequires : perl-HTML-HTML5-Entities
BuildRequires : perl-HTML-Lint
BuildRequires : perl-HTML-Parser
BuildRequires : perl-HTML-Strip
BuildRequires : perl-HTML-StripScripts
BuildRequires : perl-HTML-TableExtract
BuildRequires : perl-HTML-Tagset
BuildRequires : perl-HTML-Tiny
BuildRequires : perl-HTML-TreeBuilder
BuildRequires : perl-HTTP-Body
BuildRequires : perl-HTTP-CookieJar
BuildRequires : perl-HTTP-Cookies
BuildRequires : perl-HTTP-Daemon
BuildRequires : perl-HTTP-Date
BuildRequires : perl-HTTP-Entity-Parser
BuildRequires : perl-HTTP-Headers-Fast
BuildRequires : perl-HTTP-Message
BuildRequires : perl-HTTP-MultiPartParser
BuildRequires : perl-HTTP-Negotiate
BuildRequires : perl-HTTP-Parser-XS
BuildRequires : perl-HTTP-Request-AsCGI
BuildRequires : perl-HTTP-Server-Simple
BuildRequires : perl-HTTP-Tinyish
BuildRequires : perl-Hash-Flatten
BuildRequires : perl-Hash-Merge
BuildRequires : perl-Hash-MoreUtils
BuildRequires : perl-Hash-MultiValue
BuildRequires : perl-Hook-LexWrap
BuildRequires : perl-I18N-Charset
BuildRequires : perl-IO-AIO
BuildRequires : perl-IO-All
BuildRequires : perl-IO-Async
BuildRequires : perl-IO-Capture
BuildRequires : perl-IO-CaptureOutput
BuildRequires : perl-IO-HTML
BuildRequires : perl-IO-Interactive
BuildRequires : perl-IO-Interactive-Tiny
BuildRequires : perl-IO-Interface
BuildRequires : perl-IO-Multiplex
BuildRequires : perl-IO-Pipely
BuildRequires : perl-IO-Prompter
BuildRequires : perl-IO-Socket-INET6
BuildRequires : perl-IO-Socket-Multicast
BuildRequires : perl-IO-Socket-SSL
BuildRequires : perl-IO-Socket-Socks
BuildRequires : perl-IO-Socket-Timeout
BuildRequires : perl-IO-String
BuildRequires : perl-IO-Tee
BuildRequires : perl-IO-TieCombine
BuildRequires : perl-IO-Tty
BuildRequires : perl-IO-stringy
BuildRequires : perl-IPC-Run
BuildRequires : perl-IPC-Run3
BuildRequires : perl-IPC-ShareLite
BuildRequires : perl-IPC-Shareable
BuildRequires : perl-IPC-System-Simple
BuildRequires : perl-Image-Base
BuildRequires : perl-Image-Info
BuildRequires : perl-Image-Size
BuildRequires : perl-Image-Xbm
BuildRequires : perl-Image-Xpm
BuildRequires : perl-Import-Into
BuildRequires : perl-Importer
BuildRequires : perl-Inline
BuildRequires : perl-Inline-C
BuildRequires : perl-JSON
BuildRequires : perl-JSON-Any
BuildRequires : perl-JSON-MaybeXS
BuildRequires : perl-JSON-RPC
BuildRequires : perl-JSON-XS
BuildRequires : perl-JavaScript-Minifier-XS
BuildRequires : perl-LWP-MediaTypes
BuildRequires : perl-LWP-Protocol-https
BuildRequires : perl-LWP-Protocol-socks
BuildRequires : perl-LWP-UserAgent-Determined
BuildRequires : perl-Lchown
BuildRequires : perl-Lexical-SealRequireHints
BuildRequires : perl-Library-CallNumber-LC
BuildRequires : perl-Lingua-EN-Inflect
BuildRequires : perl-Lingua-EN-Inflect-Number
BuildRequires : perl-Lingua-Translit
BuildRequires : perl-Linux-Pid
BuildRequires : perl-List-AllUtils
BuildRequires : perl-List-Compare
BuildRequires : perl-List-MoreUtils
BuildRequires : perl-List-MoreUtils-XS
BuildRequires : perl-List-SomeUtils
BuildRequires : perl-List-SomeUtils-XS
BuildRequires : perl-List-UtilsBy
BuildRequires : perl-Locale-Maketext-Gettext
BuildRequires : perl-Locale-Maketext-Lexicon
BuildRequires : perl-Locale-Msgfmt
BuildRequires : perl-Log-Agent
BuildRequires : perl-Log-Any
BuildRequires : perl-Log-Contextual
BuildRequires : perl-Log-Dispatch
BuildRequires : perl-Log-Dispatch-Array
BuildRequires : perl-Log-Dispatch-FileRotate
BuildRequires : perl-Log-Log4perl
BuildRequires : perl-Log-Message
BuildRequires : perl-Log-Message-Simple
BuildRequires : perl-Log-Trace
BuildRequires : perl-MARC-Record
BuildRequires : perl-MIME-Base32
BuildRequires : perl-MIME-Base64
BuildRequires : perl-MIME-Base64-URLSafe
BuildRequires : perl-MIME-Charset
BuildRequires : perl-MIME-Lite
BuildRequires : perl-MIME-Types
BuildRequires : perl-MLDBM
BuildRequires : perl-MRO-Compat
BuildRequires : perl-Mail-Mailer
BuildRequires : perl-Mail-POP3Client
BuildRequires : perl-Mail-Sender
BuildRequires : perl-Mail-Sendmail
BuildRequires : perl-Math-Base-Convert
BuildRequires : perl-Math-Base36
BuildRequires : perl-Math-BigInt-GMP
BuildRequires : perl-Math-Calc-Units
BuildRequires : perl-Math-Derivative
BuildRequires : perl-Math-Polygon
BuildRequires : perl-Math-Prime-XS
BuildRequires : perl-Math-Random-ISAAC
BuildRequires : perl-Math-Random-ISAAC-XS
BuildRequires : perl-Math-Round
BuildRequires : perl-Math-Spline
BuildRequires : perl-Math-Utils
BuildRequires : perl-Math-Vec
BuildRequires : perl-Memoize-ExpireLRU
BuildRequires : perl-Meta-Builder
BuildRequires : perl-Metrics-Any
BuildRequires : perl-Minion
BuildRequires : perl-Mixin-Linewise
BuildRequires : perl-Mock-Config
BuildRequires : perl-Modern-Perl
BuildRequires : perl-Module-Build
BuildRequires : perl-Module-Build-Tiny
BuildRequires : perl-Module-CPANfile
BuildRequires : perl-Module-Extract
BuildRequires : perl-Module-Find
BuildRequires : perl-Module-Implementation
BuildRequires : perl-Module-Install
BuildRequires : perl-Module-List
BuildRequires : perl-Module-Pluggable
BuildRequires : perl-Module-Refresh
BuildRequires : perl-Module-Runtime
BuildRequires : perl-Module-Runtime-Conflicts
BuildRequires : perl-Module-ScanDeps
BuildRequires : perl-Module-Starter
BuildRequires : perl-Module-Util
BuildRequires : perl-Module-Versions-Report
BuildRequires : perl-Mojo-DOM58
BuildRequires : perl-Mojo-IOLoop-ReadWriteProcess
BuildRequires : perl-Mojo-Pg
BuildRequires : perl-Mojo-RabbitMQ-Client
BuildRequires : perl-Mojolicious
BuildRequires : perl-Mojolicious-Plugin-AssetPack
BuildRequires : perl-Mojolicious-Plugin-RenderFile
BuildRequires : perl-Moo
BuildRequires : perl-MooX-Role-Parameterized
BuildRequires : perl-Moose
BuildRequires : perl-MooseX-Role-Parameterized
BuildRequires : perl-MooseX-Role-WithOverloading
BuildRequires : perl-MooseX-Types
BuildRequires : perl-MooseX-Types-JSON
BuildRequires : perl-MooseX-Types-LoadableClass
BuildRequires : perl-MooseX-Types-Path-Class
BuildRequires : perl-Mozilla-CA
BuildRequires : perl-Net-AMQP
BuildRequires : perl-Net-Bluetooth
BuildRequires : perl-Net-CIDR-Lite
BuildRequires : perl-Net-DBus
BuildRequires : perl-Net-DNS
BuildRequires : perl-Net-DNS-Resolver-Programmable
BuildRequires : perl-Net-Daemon
BuildRequires : perl-Net-HTTP
BuildRequires : perl-Net-IDN-Encode
BuildRequires : perl-Net-INET6Glue
BuildRequires : perl-Net-IP
BuildRequires : perl-Net-Ident
BuildRequires : perl-Net-MAC
BuildRequires : perl-Net-MQTT
BuildRequires : perl-Net-NTP
BuildRequires : perl-Net-OpenID-Common
BuildRequires : perl-Net-OpenID-Consumer
BuildRequires : perl-Net-OpenSSH
BuildRequires : perl-Net-SFTP-Foreign
BuildRequires : perl-Net-SMTP-SSL
BuildRequires : perl-Net-SSH2
BuildRequires : perl-Net-SSLeay
BuildRequires : perl-Net-Server
BuildRequires : perl-Net-UPnP
BuildRequires : perl-NetAddr-IP
BuildRequires : perl-NetPacket
BuildRequires : perl-Number-Bytes-Human
BuildRequires : perl-Number-Compare
BuildRequires : perl-Number-Format
BuildRequires : perl-Number-Misc
BuildRequires : perl-Number-WithError
BuildRequires : perl-Object-Accessor
BuildRequires : perl-Object-Remote
BuildRequires : perl-Object-Signature
BuildRequires : perl-PDF-API2
BuildRequires : perl-PDF-Table
BuildRequires : perl-PDF-Writer
BuildRequires : perl-PHP-Serialization
BuildRequires : perl-POD2-Base
BuildRequires : perl-POE
BuildRequires : perl-POE-Test-Loops
BuildRequires : perl-POSIX-strftime-Compiler
BuildRequires : perl-PPI
BuildRequires : perl-Package-Constants
BuildRequires : perl-Package-DeprecationManager
BuildRequires : perl-Package-Generator
BuildRequires : perl-Package-New
BuildRequires : perl-Package-Stash
BuildRequires : perl-Package-Stash-XS
BuildRequires : perl-Package-Variant
BuildRequires : perl-PadWalker
BuildRequires : perl-Palm-PDB
BuildRequires : perl-Parallel-ForkManager
BuildRequires : perl-Parallel-Iterator
BuildRequires : perl-Params-Classify
BuildRequires : perl-Params-Util
BuildRequires : perl-Params-Validate
BuildRequires : perl-Params-ValidationCompiler
BuildRequires : perl-Parse-EDID
BuildRequires : perl-Parse-ExuberantCTags
BuildRequires : perl-Parse-RecDescent
BuildRequires : perl-Parse-Yapp
BuildRequires : perl-Path-Class
BuildRequires : perl-Path-Tiny
BuildRequires : perl-Pegex
BuildRequires : perl-Perl-Tidy
BuildRequires : perl-Perl-Version
BuildRequires : perl-Perl4-CoreLibs
BuildRequires : perl-Perl6-Export
BuildRequires : perl-PerlIO-eol
BuildRequires : perl-PerlIO-gzip
BuildRequires : perl-PerlIO-utf8_strict
BuildRequires : perl-PerlIO-via-Timeout
BuildRequires : perl-PlRPC
BuildRequires : perl-Plack
BuildRequires : perl-Pod-Constants
BuildRequires : perl-Pod-Coverage
BuildRequires : perl-Pod-LaTeX
BuildRequires : perl-Pod-POM
BuildRequires : perl-Pod-Plainer
BuildRequires : perl-Pod-Spell
BuildRequires : perl-Pod-Strip
BuildRequires : perl-PostScript-File
BuildRequires : perl-Proc-InvokeEditor
BuildRequires : perl-Proc-ProcessTable
BuildRequires : perl-Proc-Wait3
BuildRequires : perl-Protocol-OSC
BuildRequires : perl-Quota
BuildRequires : perl-Readonly
BuildRequires : perl-Redis
BuildRequires : perl-Ref-Util
BuildRequires : perl-Ref-Util-XS
BuildRequires : perl-Regexp-Common
BuildRequires : perl-Reply
BuildRequires : perl-Return-MultiLevel
BuildRequires : perl-Role-Basic
BuildRequires : perl-Role-Tiny
BuildRequires : perl-Roman
BuildRequires : perl-Router-Simple
BuildRequires : perl-SGMLS
BuildRequires : perl-SMTP-Server
BuildRequires : perl-SQL-Abstract
BuildRequires : perl-SQL-Abstract-Classic
BuildRequires : perl-SQL-SplitStatement
BuildRequires : perl-SQL-Tokenizer
BuildRequires : perl-SQL-Translator
BuildRequires : perl-SUPER
BuildRequires : perl-Scalar-String
BuildRequires : perl-Scope-Guard
BuildRequires : perl-Scope-Upper
BuildRequires : perl-Sereal
BuildRequires : perl-Sereal-Decoder
BuildRequires : perl-Sereal-Encoder
BuildRequires : perl-Set-Object
BuildRequires : perl-Set-Scalar
BuildRequires : perl-Smart-Comments
BuildRequires : perl-Socket-MsgHdr
BuildRequires : perl-Socket6
BuildRequires : perl-Software-License
BuildRequires : perl-Sort-Key
BuildRequires : perl-Sort-Naturally
BuildRequires : perl-Sort-Versions
BuildRequires : perl-Specio
BuildRequires : perl-Spiffy
BuildRequires : perl-Statistics-Basic
BuildRequires : perl-Statistics-CaseResampling
BuildRequires : perl-Storable
BuildRequires : perl-Stream-Buffered
BuildRequires : perl-String-Approx
BuildRequires : perl-String-CamelCase
BuildRequires : perl-String-Escape
BuildRequires : perl-String-Expand
BuildRequires : perl-String-Format
BuildRequires : perl-String-Random
BuildRequires : perl-String-ShellQuote
BuildRequires : perl-String-Similarity
BuildRequires : perl-String-Util
BuildRequires : perl-Struct-Dumb
BuildRequires : perl-Sub-Exporter
BuildRequires : perl-Sub-Exporter-ForMethods
BuildRequires : perl-Sub-Exporter-Progressive
BuildRequires : perl-Sub-Identify
BuildRequires : perl-Sub-Info
BuildRequires : perl-Sub-Install
BuildRequires : perl-Sub-Name
BuildRequires : perl-Sub-Quote
BuildRequires : perl-Sub-Uplevel
BuildRequires : perl-Switch
BuildRequires : perl-Symbol-Global-Name
BuildRequires : perl-Sys-Hostname-Long
BuildRequires : perl-Sys-MemInfo
BuildRequires : perl-Sys-Mmap
BuildRequires : perl-Sys-SigAction
BuildRequires : perl-Sys-Statistics-Linux
BuildRequires : perl-System-Command
BuildRequires : perl-Systemd-Daemon
BuildRequires : perl-TAP-Formatter-HTML
BuildRequires : perl-TAP-Harness-Archive
BuildRequires : perl-Taint-Util
BuildRequires : perl-Task-Weaken
BuildRequires : perl-Template-Toolkit
BuildRequires : perl-Term-ProgressBar
BuildRequires : perl-Term-ReadKey
BuildRequires : perl-Term-ReadLine-Gnu
BuildRequires : perl-Term-ReadPassword
BuildRequires : perl-Term-Shell
BuildRequires : perl-Term-ShellUI
BuildRequires : perl-Term-Size-Perl
BuildRequires : perl-Term-Table
BuildRequires : perl-Term-UI
BuildRequires : perl-Test-Assertions
BuildRequires : perl-Test-Base
BuildRequires : perl-Test-CleanNamespaces
BuildRequires : perl-Test-Command
BuildRequires : perl-Test-Compile
BuildRequires : perl-Test-Deep
BuildRequires : perl-Test-DiagINC
BuildRequires : perl-Test-Differences
BuildRequires : perl-Test-Exception
BuildRequires : perl-Test-FailWarnings
BuildRequires : perl-Test-Fatal
BuildRequires : perl-Test-File
BuildRequires : perl-Test-File-ShareDir-Dist
BuildRequires : perl-Test-Fork
BuildRequires : perl-Test-Identity
BuildRequires : perl-Test-Inter
BuildRequires : perl-Test-LeakTrace
BuildRequires : perl-Test-LectroTest
BuildRequires : perl-Test-LongString
BuildRequires : perl-Test-Manifest
BuildRequires : perl-Test-Memory-Cycle
BuildRequires : perl-Test-MemoryGrowth
BuildRequires : perl-Test-Metrics-Any
BuildRequires : perl-Test-MockModule
BuildRequires : perl-Test-MockTime
BuildRequires : perl-Test-More-UTF8
BuildRequires : perl-Test-Most
BuildRequires : perl-Test-Needs
BuildRequires : perl-Test-NoWarnings
BuildRequires : perl-Test-Number-Delta
BuildRequires : perl-Test-Object
BuildRequires : perl-Test-Output
BuildRequires : perl-Test-Pod
BuildRequires : perl-Test-Pod-Coverage
BuildRequires : perl-Test-Refcount
BuildRequires : perl-Test-Reporter
BuildRequires : perl-Test-Requires
BuildRequires : perl-Test-RequiresInternet
BuildRequires : perl-Test-SharedFork
BuildRequires : perl-Test-Simple
BuildRequires : perl-Test-Strict
BuildRequires : perl-Test-SubCalls
BuildRequires : perl-Test-Synopsis
BuildRequires : perl-Test-TCP
BuildRequires : perl-Test-Taint
BuildRequires : perl-Test-Toolbox
BuildRequires : perl-Test-Trap
BuildRequires : perl-Test-UseAllModules
BuildRequires : perl-Test-Warn
BuildRequires : perl-Test-Warnings
BuildRequires : perl-Test-Without-Module
BuildRequires : perl-Test-YAML
BuildRequires : perl-Test-utf8
BuildRequires : perl-Test2-Suite
BuildRequires : perl-Text-Autoformat
BuildRequires : perl-Text-Brew
BuildRequires : perl-Text-CSV
BuildRequires : perl-Text-CSV-Encoded
BuildRequires : perl-Text-CSV_XS
BuildRequires : perl-Text-CharWidth
BuildRequires : perl-Text-Diff
BuildRequires : perl-Text-FindIndent
BuildRequires : perl-Text-Format
BuildRequires : perl-Text-Glob
BuildRequires : perl-Text-Haml
BuildRequires : perl-Text-Levenshtein
BuildRequires : perl-Text-Levenshtein-Damerau
BuildRequires : perl-Text-Markdown
BuildRequires : perl-Text-PDF
BuildRequires : perl-Text-Quoted
BuildRequires : perl-Text-RecordParser
BuildRequires : perl-Text-Reform
BuildRequires : perl-Text-Roman
BuildRequires : perl-Text-TabularDisplay
BuildRequires : perl-Text-Template
BuildRequires : perl-Text-Trim
BuildRequires : perl-Text-Unidecode
BuildRequires : perl-Text-WrapI18N
BuildRequires : perl-Text-Wrapper
BuildRequires : perl-Tie-Cycle
BuildRequires : perl-Tie-IxHash
BuildRequires : perl-Tie-Simple
BuildRequires : perl-Time-Duration
BuildRequires : perl-Time-Duration-Parse
BuildRequires : perl-Time-ParseDate
BuildRequires : perl-Time-Period
BuildRequires : perl-TimeDate
BuildRequires : perl-Tk
BuildRequires : perl-Tk-DoubleClick
BuildRequires : perl-Try-Tiny
BuildRequires : perl-Type-Tiny
BuildRequires : perl-Type-Tiny-XS
BuildRequires : perl-Types-Path-Tiny
BuildRequires : perl-Types-Serialiser
BuildRequires : perl-UNIVERSAL-can
BuildRequires : perl-UNIVERSAL-require
BuildRequires : perl-URI
BuildRequires : perl-URI-Encode
BuildRequires : perl-URI-Escape-XS
BuildRequires : perl-URI-Fetch
BuildRequires : perl-URI-Find
BuildRequires : perl-UUID-Tiny
BuildRequires : perl-Unicode-LineBreak
BuildRequires : perl-Unicode-Map
BuildRequires : perl-Variable-Magic
BuildRequires : perl-WWW-Form-UrlEncoded
BuildRequires : perl-WWW-Form-UrlEncoded-XS
BuildRequires : perl-WWW-Mechanize
BuildRequires : perl-WWW-RobotRules
BuildRequires : perl-Want
BuildRequires : perl-X11-Protocol
BuildRequires : perl-XML-Atom
BuildRequires : perl-XML-DOM
BuildRequires : perl-XML-Dumper
BuildRequires : perl-XML-Feed
BuildRequires : perl-XML-Filter-BufferText
BuildRequires : perl-XML-Handler-Trees
BuildRequires : perl-XML-LibXML
BuildRequires : perl-XML-LibXML-Simple
BuildRequires : perl-XML-NamespaceSupport
BuildRequires : perl-XML-Parser
BuildRequires : perl-XML-Parser-Lite
BuildRequires : perl-XML-RSS
BuildRequires : perl-XML-RSS-LibXML
BuildRequires : perl-XML-RegExp
BuildRequires : perl-XML-SAX
BuildRequires : perl-XML-SAX-Base
BuildRequires : perl-XML-SAX-Expat
BuildRequires : perl-XML-SAX-ExpatXS
BuildRequires : perl-XML-SAX-Writer
BuildRequires : perl-XML-Simple
BuildRequires : perl-XML-SimpleObject
BuildRequires : perl-XML-Twig
BuildRequires : perl-XML-Writer
BuildRequires : perl-XML-XPath
BuildRequires : perl-XML-XPathEngine
BuildRequires : perl-XString
BuildRequires : perl-YAML
BuildRequires : perl-YAML-LibYAML
BuildRequires : perl-YAML-PP
BuildRequires : perl-YAML-Syck
BuildRequires : perl-YAML-Tiny
BuildRequires : perl-accessors
BuildRequires : perl-aliased
BuildRequires : perl-autobox
BuildRequires : perl-autovivification
BuildRequires : perl-bareword-filehandles
BuildRequires : perl-boolean
BuildRequires : perl-common-sense
BuildRequires : perl-constant-defer
BuildRequires : perl-curry
BuildRequires : perl-gettext
BuildRequires : perl-inc-latest
BuildRequires : perl-indirect
BuildRequires : perl-latest
BuildRequires : perl-libwww-perl
BuildRequires : perl-libxml-perl
BuildRequires : perl-local-lib
BuildRequires : perl-man
BuildRequires : perl-multidimensional
BuildRequires : perl-namespace-autoclean
BuildRequires : perl-namespace-clean
BuildRequires : perl-pmtools
BuildRequires : perl-prefork
BuildRequires : perl-strictures
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(libbrotlicommon)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pluggy
BuildRequires : popt-dev
BuildRequires : popt-staticdev
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : readline-dev
BuildRequires : readline-dev32
BuildRequires : rpm-dev
BuildRequires : rsync
BuildRequires : rtmpdump
BuildRequires : rtmpdump-dev
BuildRequires : rtmpdump-staticdev
BuildRequires : setuptools
BuildRequires : sqlite-autoconf
BuildRequires : sqlite-autoconf-dev
BuildRequires : sqlite-autoconf-staticdev
BuildRequires : sshpass
BuildRequires : sshtunnel
BuildRequires : stunnel
BuildRequires : swig
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : texinfo
BuildRequires : time
BuildRequires : tk
BuildRequires : tox
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : virtualenv
BuildRequires : xattr
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-dev
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xmlto
BuildRequires : xz-dev
BuildRequires : xz-dev32
BuildRequires : xz-staticdev
BuildRequires : yasm
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
BuildRequires : zlib-staticdev
BuildRequires : zlib-staticdev32
BuildRequires : zstd-dev
BuildRequires : zstd-dev32
BuildRequires : zstd-staticdev
BuildRequires : zstd-staticdev32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Remove-use-of-DES.patch
Patch2: 0002-Add-pacrunner-call-for-autoproxy-resolution.patch
Patch3: 0003-Check-the-state-file-pacdiscovery-sets.patch
Patch4: 0004-Avoid-stripping-the-g-option.patch
Patch5: 0001-Open-library-file-descriptors-with-O_CLOEXEC.patch
Patch6: 0001-http2-test-ipv4-only.patch

%description
_   _ ____  _
___| | | |  _ \| |
/ __| | | | |_) | |
| (__| |_| |  _ <| |___
\___|\___/|_| \_\_____|

%package bin
Summary: bin components for the curl package.
Group: Binaries

%description bin
bin components for the curl package.


%package dev
Summary: dev components for the curl package.
Group: Development
Requires: curl-lib = %{version}-%{release}
Requires: curl-bin = %{version}-%{release}
Provides: curl-devel = %{version}-%{release}
Requires: curl = %{version}-%{release}

%description dev
dev components for the curl package.


%package dev32
Summary: dev32 components for the curl package.
Group: Default
Requires: curl-lib32 = %{version}-%{release}
Requires: curl-bin = %{version}-%{release}
Requires: curl-dev = %{version}-%{release}

%description dev32
dev32 components for the curl package.


%package lib
Summary: lib components for the curl package.
Group: Libraries

%description lib
lib components for the curl package.


%package lib32
Summary: lib32 components for the curl package.
Group: Default

%description lib32
lib32 components for the curl package.


%package man
Summary: man components for the curl package.
Group: Default

%description man
man components for the curl package.


%package staticdev
Summary: staticdev components for the curl package.
Group: Default
Requires: curl-dev = %{version}-%{release}

%description staticdev
staticdev components for the curl package.


%prep
%setup -q -n curl
cd %{_builddir}/curl
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
pushd %{_builddir}
cp -a %{_builddir}/curl build32
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1630136123
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage -fprofile-partial-training -fprofile-correction -freorder-functions --coverage -lgcov"
export CFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export FCFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export FFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export LDFLAGS_GENERATE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_GEN"
export LIBS="-lgcov"
## pgo use
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -Ofast -ffast-math
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
## -pthread -lpthread
## -Wl,-Bsymbolic-functions
export PGO_USE="-Wmissing-profile -Wcoverage-mismatch -fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-partial-training -fprofile-correction -freorder-functions"
export CFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode %{nil}
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags_pgo end
sd -r '\s--dirty\s' ' ' .
sd -r 'git describe' 'git describe --abbrev=0' .
sd --flags mi '^AC_INIT\((.*\n.*\)|.*\))' '$0\nAM_MAINTAINER_MODE([disable])' configure.ac
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%reconfigure  --enable-shared \
--enable-static \
--disable-gopher \
--disable-ipv6 \
--disable-ldap \
--disable-ntlm-wb \
--disable-pop3 \
--disable-smb \
--disable-telnet \
--disable-tftp \
--disable-werror \
--disable-gcc-warnings \
--enable-cookies \
--enable-crypto-auth \
--enable-dict \
--enable-doh \
--enable-http-auth \
--enable-libcurl-option \
--enable-mime \
--enable-negotiate \
--enable-optimize \
--enable-progress-meter \
--enable-proxy \
--enable-pthreads \
--enable-symbol-hiding \
--enable-threaded-resolver \
--enable-tls-srp \
--enable-versioned-symbols \
--with-brotli \
--with-ca-path=/var/cache/ca-certs/anchors \
--with-gssapi \
--with-libidn2 \
--with-nghttp2 \
--with-openssl=/usr \
--with-zlib \
--with-zstd \
--with-librtmp=/usr \
--without-winidn
## make_prepend64 content
# find . -type f -name 'Makefile' -exec sed -i 's:-lssl\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libssl.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lcrypto\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libcrypto.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lnghttp2\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libnghttp2.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lsqlite3\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libsqlite3.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lidn2\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libidn2.a,/usr/lib64/libunistring.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lunistring\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libunistring.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lbrotlidec\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libbrotlidec-static.a,/usr/lib64/libbrotlicommon-static.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lzstd\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libzstd.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lz\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libz.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# sd "\-lssl" -- "-Wl,--whole-archive,--start-group,/usr/lib64/libssl.a,/usr/lib64/libcrypto.a,/usr/lib64/libz.a,--end-group,--no-whole-archive" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
find . -type f -name 'Makefile' -exec sed -i 's:-lssl\b:/usr/lib64/libssl.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lcrypto\b:/usr/lib64/libcrypto.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lnghttp2\b:/usr/lib64/libnghttp2.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lidn2\b:/usr/lib64/libidn2.a /usr/lib64/libunistring.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lunistring\b:/usr/lib64/libunistring.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lbrotlidec\b:/usr/lib64/libbrotlidec-static.a /usr/lib64/libbrotlicommon-static.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lzstd\b:/usr/lib64/libzstd.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lz\b:/usr/lib64/libz.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lsqlite3\b:/usr/lib64/libsqlite3.a:g' {} \;
sd "\-lrtmp" -- "/usr/lib64/librtmp.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lgssapi_krb5" -- "-Wl,--whole-archive,--as-needed,--start-group,/usr/lib64/libgssapi_krb5.a,/usr/lib64/libkrb5.a,/usr/lib64/libkeyutils.a,-lresolv,/usr/lib64/libk5crypto.a,/usr/lib64/libcom_err.a,/usr/lib64/libkrb5support.a,--end-group,--no-whole-archive" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lkrb5" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lkeyutils" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lk5crypto" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lcom_err" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
## make_prepend64 end
## make_macro content
make -j16 V=1 VERBOSE=1
## make_macro end

## profile_payload start
unset LD_LIBRARY_PATH
unset LIBRARY_PATH
exit
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
export LD_LIBRARY_PATH="/builddir/build/BUILD/curl/lib/.libs/"
export LIBRARY_PATH="/builddir/build/BUILD/curl/lib/.libs/"
export $(dbus-launch)
make -j1 test V=1 VERBOSE=1 || :
# make -j1 test-torture V=1 VERBOSE=1 || :
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/haswell/pulseaudio:/usr/lib64/haswell/alsa-lib:/usr/lib64/haswell/gstreamer-1.0:/usr/lib64/haswell/pipewire-0.3:/usr/lib64/haswell/spa-0.2:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
## profile_payload end
make clean || :
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%reconfigure  --enable-shared \
--enable-static \
--disable-gopher \
--disable-ipv6 \
--disable-ldap \
--disable-ntlm-wb \
--disable-pop3 \
--disable-smb \
--disable-telnet \
--disable-tftp \
--disable-werror \
--disable-gcc-warnings \
--enable-cookies \
--enable-crypto-auth \
--enable-dict \
--enable-doh \
--enable-http-auth \
--enable-libcurl-option \
--enable-mime \
--enable-negotiate \
--enable-optimize \
--enable-progress-meter \
--enable-proxy \
--enable-pthreads \
--enable-symbol-hiding \
--enable-threaded-resolver \
--enable-tls-srp \
--enable-versioned-symbols \
--with-brotli \
--with-ca-path=/var/cache/ca-certs/anchors \
--with-gssapi \
--with-libidn2 \
--with-nghttp2 \
--with-openssl=/usr \
--with-zlib \
--with-zstd \
--with-librtmp=/usr \
--without-winidn
## make_prepend64 content
# find . -type f -name 'Makefile' -exec sed -i 's:-lssl\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libssl.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lcrypto\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libcrypto.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lnghttp2\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libnghttp2.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lsqlite3\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libsqlite3.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lidn2\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libidn2.a,/usr/lib64/libunistring.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lunistring\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libunistring.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lbrotlidec\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libbrotlidec-static.a,/usr/lib64/libbrotlicommon-static.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lzstd\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libzstd.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# find . -type f -name 'Makefile' -exec sed -i 's:-lz\b:-Wl,--whole-archive,--as-needed,/usr/lib64/libz.a,-lpthread,-ldl,-lm,-lmvec,--no-whole-archive:g' {} \;
# sd "\-lssl" -- "-Wl,--whole-archive,--start-group,/usr/lib64/libssl.a,/usr/lib64/libcrypto.a,/usr/lib64/libz.a,--end-group,--no-whole-archive" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
find . -type f -name 'Makefile' -exec sed -i 's:-lssl\b:/usr/lib64/libssl.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lcrypto\b:/usr/lib64/libcrypto.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lnghttp2\b:/usr/lib64/libnghttp2.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lidn2\b:/usr/lib64/libidn2.a /usr/lib64/libunistring.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lunistring\b:/usr/lib64/libunistring.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lbrotlidec\b:/usr/lib64/libbrotlidec-static.a /usr/lib64/libbrotlicommon-static.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lzstd\b:/usr/lib64/libzstd.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lz\b:/usr/lib64/libz.a:g' {} \;
find . -type f -name 'Makefile' -exec sed -i 's:-lsqlite3\b:/usr/lib64/libsqlite3.a:g' {} \;
sd "\-lrtmp" -- "/usr/lib64/librtmp.a" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lgssapi_krb5" -- "-Wl,--whole-archive,--as-needed,--start-group,/usr/lib64/libgssapi_krb5.a,/usr/lib64/libkrb5.a,/usr/lib64/libkeyutils.a,-lresolv,/usr/lib64/libk5crypto.a,/usr/lib64/libcom_err.a,/usr/lib64/libkrb5support.a,--end-group,--no-whole-archive" $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lkrb5" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lkeyutils" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lk5crypto" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
sd "\-lcom_err" -- " " $(fd -uu --follow .*Makefile$) $(fd -uu --follow .*pro$) $(fd -uu --follow .*mk$)
## make_prepend64 end
## make_macro content
make -j16 V=1 VERBOSE=1
## make_macro end
fi

pushd ../build32/
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
unset LD_LIBRARY_PATH
unset LIBRARY_PATH
unset CPATH
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
unset ASFLAGS
unset CFLAGS
unset CXXFLAGS
unset FCFLAGS
unset FFLAGS
unset CFFLAGS
unset LDFLAGS
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -march=native -mtune=native -m32 -mstackrealign"
export CXXFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -march=native -mtune=native -m32 -mstackrealign"
export FCFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -march=native -mtune=native -m32 -mstackrealign"
export FFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -march=native -mtune=native -m32 -mstackrealign"
export CFFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -march=native -mtune=native -m32 -mstackrealign"
export LDFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -march=native -mtune=native -m32 -mstackrealign"
sd --flags mi '^AC_INIT\((.*\n.*\)|.*\))' '$0\nAM_MAINTAINER_MODE([disable])' configure.ac
%reconfigure  --enable-shared \
--disable-static \
--disable-gopher \
--disable-ipv6 \
--disable-ldap \
--disable-ntlm-wb \
--disable-pop3 \
--disable-gcc-warnings \
--disable-smb \
--disable-telnet \
--disable-tftp \
--enable-negotiate \
--enable-proxy \
--enable-symbol-hiding \
--enable-threaded-resolver \
--with-brotli \
--with-ca-path=/var/cache/ca-certs/anchors \
--with-libidn2 \
--with-openssl=/usr \
--without-winidn \
--with-zlib \
--with-zstd --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}  V=1 VERBOSE=1  V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1630136123
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
    pushd %{buildroot}/usr/lib32/pkgconfig
    for i in *.pc ; do ln -s $i 32$i ; done
    popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/curl
/usr/bin/curl-config

%files dev
%defattr(-,root,root,-)
/usr/include/curl/curl.h
/usr/include/curl/curlver.h
/usr/include/curl/easy.h
/usr/include/curl/mprintf.h
/usr/include/curl/multi.h
/usr/include/curl/options.h
/usr/include/curl/stdcheaders.h
/usr/include/curl/system.h
/usr/include/curl/typecheck-gcc.h
/usr/include/curl/urlapi.h
/usr/lib64/libcurl.so
/usr/lib64/pkgconfig/libcurl.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libcurl.so
/usr/lib32/pkgconfig/32libcurl.pc
/usr/lib32/pkgconfig/libcurl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcurl.so.4
/usr/lib64/libcurl.so.4.7.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libcurl.so.4
/usr/lib32/libcurl.so.4.7.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/curl-config.1
/usr/share/man/man1/curl.1
/usr/share/man/man3/CURLINFO_ACTIVESOCKET.3
/usr/share/man/man3/CURLINFO_APPCONNECT_TIME.3
/usr/share/man/man3/CURLINFO_APPCONNECT_TIME_T.3
/usr/share/man/man3/CURLINFO_CERTINFO.3
/usr/share/man/man3/CURLINFO_CONDITION_UNMET.3
/usr/share/man/man3/CURLINFO_CONNECT_TIME.3
/usr/share/man/man3/CURLINFO_CONNECT_TIME_T.3
/usr/share/man/man3/CURLINFO_CONTENT_LENGTH_DOWNLOAD.3
/usr/share/man/man3/CURLINFO_CONTENT_LENGTH_DOWNLOAD_T.3
/usr/share/man/man3/CURLINFO_CONTENT_LENGTH_UPLOAD.3
/usr/share/man/man3/CURLINFO_CONTENT_LENGTH_UPLOAD_T.3
/usr/share/man/man3/CURLINFO_CONTENT_TYPE.3
/usr/share/man/man3/CURLINFO_COOKIELIST.3
/usr/share/man/man3/CURLINFO_EFFECTIVE_METHOD.3
/usr/share/man/man3/CURLINFO_EFFECTIVE_URL.3
/usr/share/man/man3/CURLINFO_FILETIME.3
/usr/share/man/man3/CURLINFO_FILETIME_T.3
/usr/share/man/man3/CURLINFO_FTP_ENTRY_PATH.3
/usr/share/man/man3/CURLINFO_HEADER_SIZE.3
/usr/share/man/man3/CURLINFO_HTTPAUTH_AVAIL.3
/usr/share/man/man3/CURLINFO_HTTP_CONNECTCODE.3
/usr/share/man/man3/CURLINFO_HTTP_VERSION.3
/usr/share/man/man3/CURLINFO_LASTSOCKET.3
/usr/share/man/man3/CURLINFO_LOCAL_IP.3
/usr/share/man/man3/CURLINFO_LOCAL_PORT.3
/usr/share/man/man3/CURLINFO_NAMELOOKUP_TIME.3
/usr/share/man/man3/CURLINFO_NAMELOOKUP_TIME_T.3
/usr/share/man/man3/CURLINFO_NUM_CONNECTS.3
/usr/share/man/man3/CURLINFO_OS_ERRNO.3
/usr/share/man/man3/CURLINFO_PRETRANSFER_TIME.3
/usr/share/man/man3/CURLINFO_PRETRANSFER_TIME_T.3
/usr/share/man/man3/CURLINFO_PRIMARY_IP.3
/usr/share/man/man3/CURLINFO_PRIMARY_PORT.3
/usr/share/man/man3/CURLINFO_PRIVATE.3
/usr/share/man/man3/CURLINFO_PROTOCOL.3
/usr/share/man/man3/CURLINFO_PROXYAUTH_AVAIL.3
/usr/share/man/man3/CURLINFO_PROXY_ERROR.3
/usr/share/man/man3/CURLINFO_PROXY_SSL_VERIFYRESULT.3
/usr/share/man/man3/CURLINFO_REDIRECT_COUNT.3
/usr/share/man/man3/CURLINFO_REDIRECT_TIME.3
/usr/share/man/man3/CURLINFO_REDIRECT_TIME_T.3
/usr/share/man/man3/CURLINFO_REDIRECT_URL.3
/usr/share/man/man3/CURLINFO_REFERER.3
/usr/share/man/man3/CURLINFO_REQUEST_SIZE.3
/usr/share/man/man3/CURLINFO_RESPONSE_CODE.3
/usr/share/man/man3/CURLINFO_RETRY_AFTER.3
/usr/share/man/man3/CURLINFO_RTSP_CLIENT_CSEQ.3
/usr/share/man/man3/CURLINFO_RTSP_CSEQ_RECV.3
/usr/share/man/man3/CURLINFO_RTSP_SERVER_CSEQ.3
/usr/share/man/man3/CURLINFO_RTSP_SESSION_ID.3
/usr/share/man/man3/CURLINFO_SCHEME.3
/usr/share/man/man3/CURLINFO_SIZE_DOWNLOAD.3
/usr/share/man/man3/CURLINFO_SIZE_DOWNLOAD_T.3
/usr/share/man/man3/CURLINFO_SIZE_UPLOAD.3
/usr/share/man/man3/CURLINFO_SIZE_UPLOAD_T.3
/usr/share/man/man3/CURLINFO_SPEED_DOWNLOAD.3
/usr/share/man/man3/CURLINFO_SPEED_DOWNLOAD_T.3
/usr/share/man/man3/CURLINFO_SPEED_UPLOAD.3
/usr/share/man/man3/CURLINFO_SPEED_UPLOAD_T.3
/usr/share/man/man3/CURLINFO_SSL_ENGINES.3
/usr/share/man/man3/CURLINFO_SSL_VERIFYRESULT.3
/usr/share/man/man3/CURLINFO_STARTTRANSFER_TIME.3
/usr/share/man/man3/CURLINFO_STARTTRANSFER_TIME_T.3
/usr/share/man/man3/CURLINFO_TLS_SESSION.3
/usr/share/man/man3/CURLINFO_TLS_SSL_PTR.3
/usr/share/man/man3/CURLINFO_TOTAL_TIME.3
/usr/share/man/man3/CURLINFO_TOTAL_TIME_T.3
/usr/share/man/man3/CURLMOPT_CHUNK_LENGTH_PENALTY_SIZE.3
/usr/share/man/man3/CURLMOPT_CONTENT_LENGTH_PENALTY_SIZE.3
/usr/share/man/man3/CURLMOPT_MAXCONNECTS.3
/usr/share/man/man3/CURLMOPT_MAX_CONCURRENT_STREAMS.3
/usr/share/man/man3/CURLMOPT_MAX_HOST_CONNECTIONS.3
/usr/share/man/man3/CURLMOPT_MAX_PIPELINE_LENGTH.3
/usr/share/man/man3/CURLMOPT_MAX_TOTAL_CONNECTIONS.3
/usr/share/man/man3/CURLMOPT_PIPELINING.3
/usr/share/man/man3/CURLMOPT_PIPELINING_SERVER_BL.3
/usr/share/man/man3/CURLMOPT_PIPELINING_SITE_BL.3
/usr/share/man/man3/CURLMOPT_PUSHDATA.3
/usr/share/man/man3/CURLMOPT_PUSHFUNCTION.3
/usr/share/man/man3/CURLMOPT_SOCKETDATA.3
/usr/share/man/man3/CURLMOPT_SOCKETFUNCTION.3
/usr/share/man/man3/CURLMOPT_TIMERDATA.3
/usr/share/man/man3/CURLMOPT_TIMERFUNCTION.3
/usr/share/man/man3/CURLOPT_ABSTRACT_UNIX_SOCKET.3
/usr/share/man/man3/CURLOPT_ACCEPTTIMEOUT_MS.3
/usr/share/man/man3/CURLOPT_ACCEPT_ENCODING.3
/usr/share/man/man3/CURLOPT_ADDRESS_SCOPE.3
/usr/share/man/man3/CURLOPT_ALTSVC.3
/usr/share/man/man3/CURLOPT_ALTSVC_CTRL.3
/usr/share/man/man3/CURLOPT_APPEND.3
/usr/share/man/man3/CURLOPT_AUTOREFERER.3
/usr/share/man/man3/CURLOPT_AWS_SIGV4.3
/usr/share/man/man3/CURLOPT_BUFFERSIZE.3
/usr/share/man/man3/CURLOPT_CAINFO.3
/usr/share/man/man3/CURLOPT_CAINFO_BLOB.3
/usr/share/man/man3/CURLOPT_CAPATH.3
/usr/share/man/man3/CURLOPT_CERTINFO.3
/usr/share/man/man3/CURLOPT_CHUNK_BGN_FUNCTION.3
/usr/share/man/man3/CURLOPT_CHUNK_DATA.3
/usr/share/man/man3/CURLOPT_CHUNK_END_FUNCTION.3
/usr/share/man/man3/CURLOPT_CLOSESOCKETDATA.3
/usr/share/man/man3/CURLOPT_CLOSESOCKETFUNCTION.3
/usr/share/man/man3/CURLOPT_CONNECTTIMEOUT.3
/usr/share/man/man3/CURLOPT_CONNECTTIMEOUT_MS.3
/usr/share/man/man3/CURLOPT_CONNECT_ONLY.3
/usr/share/man/man3/CURLOPT_CONNECT_TO.3
/usr/share/man/man3/CURLOPT_CONV_FROM_NETWORK_FUNCTION.3
/usr/share/man/man3/CURLOPT_CONV_FROM_UTF8_FUNCTION.3
/usr/share/man/man3/CURLOPT_CONV_TO_NETWORK_FUNCTION.3
/usr/share/man/man3/CURLOPT_COOKIE.3
/usr/share/man/man3/CURLOPT_COOKIEFILE.3
/usr/share/man/man3/CURLOPT_COOKIEJAR.3
/usr/share/man/man3/CURLOPT_COOKIELIST.3
/usr/share/man/man3/CURLOPT_COOKIESESSION.3
/usr/share/man/man3/CURLOPT_COPYPOSTFIELDS.3
/usr/share/man/man3/CURLOPT_CRLF.3
/usr/share/man/man3/CURLOPT_CRLFILE.3
/usr/share/man/man3/CURLOPT_CURLU.3
/usr/share/man/man3/CURLOPT_CUSTOMREQUEST.3
/usr/share/man/man3/CURLOPT_DEBUGDATA.3
/usr/share/man/man3/CURLOPT_DEBUGFUNCTION.3
/usr/share/man/man3/CURLOPT_DEFAULT_PROTOCOL.3
/usr/share/man/man3/CURLOPT_DIRLISTONLY.3
/usr/share/man/man3/CURLOPT_DISALLOW_USERNAME_IN_URL.3
/usr/share/man/man3/CURLOPT_DNS_CACHE_TIMEOUT.3
/usr/share/man/man3/CURLOPT_DNS_INTERFACE.3
/usr/share/man/man3/CURLOPT_DNS_LOCAL_IP4.3
/usr/share/man/man3/CURLOPT_DNS_LOCAL_IP6.3
/usr/share/man/man3/CURLOPT_DNS_SERVERS.3
/usr/share/man/man3/CURLOPT_DNS_SHUFFLE_ADDRESSES.3
/usr/share/man/man3/CURLOPT_DNS_USE_GLOBAL_CACHE.3
/usr/share/man/man3/CURLOPT_DOH_SSL_VERIFYHOST.3
/usr/share/man/man3/CURLOPT_DOH_SSL_VERIFYPEER.3
/usr/share/man/man3/CURLOPT_DOH_SSL_VERIFYSTATUS.3
/usr/share/man/man3/CURLOPT_DOH_URL.3
/usr/share/man/man3/CURLOPT_EGDSOCKET.3
/usr/share/man/man3/CURLOPT_ERRORBUFFER.3
/usr/share/man/man3/CURLOPT_EXPECT_100_TIMEOUT_MS.3
/usr/share/man/man3/CURLOPT_FAILONERROR.3
/usr/share/man/man3/CURLOPT_FILETIME.3
/usr/share/man/man3/CURLOPT_FNMATCH_DATA.3
/usr/share/man/man3/CURLOPT_FNMATCH_FUNCTION.3
/usr/share/man/man3/CURLOPT_FOLLOWLOCATION.3
/usr/share/man/man3/CURLOPT_FORBID_REUSE.3
/usr/share/man/man3/CURLOPT_FRESH_CONNECT.3
/usr/share/man/man3/CURLOPT_FTPPORT.3
/usr/share/man/man3/CURLOPT_FTPSSLAUTH.3
/usr/share/man/man3/CURLOPT_FTP_ACCOUNT.3
/usr/share/man/man3/CURLOPT_FTP_ALTERNATIVE_TO_USER.3
/usr/share/man/man3/CURLOPT_FTP_CREATE_MISSING_DIRS.3
/usr/share/man/man3/CURLOPT_FTP_FILEMETHOD.3
/usr/share/man/man3/CURLOPT_FTP_RESPONSE_TIMEOUT.3
/usr/share/man/man3/CURLOPT_FTP_SKIP_PASV_IP.3
/usr/share/man/man3/CURLOPT_FTP_SSL_CCC.3
/usr/share/man/man3/CURLOPT_FTP_USE_EPRT.3
/usr/share/man/man3/CURLOPT_FTP_USE_EPSV.3
/usr/share/man/man3/CURLOPT_FTP_USE_PRET.3
/usr/share/man/man3/CURLOPT_GSSAPI_DELEGATION.3
/usr/share/man/man3/CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS.3
/usr/share/man/man3/CURLOPT_HAPROXYPROTOCOL.3
/usr/share/man/man3/CURLOPT_HEADER.3
/usr/share/man/man3/CURLOPT_HEADERDATA.3
/usr/share/man/man3/CURLOPT_HEADERFUNCTION.3
/usr/share/man/man3/CURLOPT_HEADEROPT.3
/usr/share/man/man3/CURLOPT_HSTS.3
/usr/share/man/man3/CURLOPT_HSTSREADDATA.3
/usr/share/man/man3/CURLOPT_HSTSREADFUNCTION.3
/usr/share/man/man3/CURLOPT_HSTSWRITEDATA.3
/usr/share/man/man3/CURLOPT_HSTSWRITEFUNCTION.3
/usr/share/man/man3/CURLOPT_HSTS_CTRL.3
/usr/share/man/man3/CURLOPT_HTTP09_ALLOWED.3
/usr/share/man/man3/CURLOPT_HTTP200ALIASES.3
/usr/share/man/man3/CURLOPT_HTTPAUTH.3
/usr/share/man/man3/CURLOPT_HTTPGET.3
/usr/share/man/man3/CURLOPT_HTTPHEADER.3
/usr/share/man/man3/CURLOPT_HTTPPOST.3
/usr/share/man/man3/CURLOPT_HTTPPROXYTUNNEL.3
/usr/share/man/man3/CURLOPT_HTTP_CONTENT_DECODING.3
/usr/share/man/man3/CURLOPT_HTTP_TRANSFER_DECODING.3
/usr/share/man/man3/CURLOPT_HTTP_VERSION.3
/usr/share/man/man3/CURLOPT_IGNORE_CONTENT_LENGTH.3
/usr/share/man/man3/CURLOPT_INFILESIZE.3
/usr/share/man/man3/CURLOPT_INFILESIZE_LARGE.3
/usr/share/man/man3/CURLOPT_INTERFACE.3
/usr/share/man/man3/CURLOPT_INTERLEAVEDATA.3
/usr/share/man/man3/CURLOPT_INTERLEAVEFUNCTION.3
/usr/share/man/man3/CURLOPT_IOCTLDATA.3
/usr/share/man/man3/CURLOPT_IOCTLFUNCTION.3
/usr/share/man/man3/CURLOPT_IPRESOLVE.3
/usr/share/man/man3/CURLOPT_ISSUERCERT.3
/usr/share/man/man3/CURLOPT_ISSUERCERT_BLOB.3
/usr/share/man/man3/CURLOPT_KEEP_SENDING_ON_ERROR.3
/usr/share/man/man3/CURLOPT_KEYPASSWD.3
/usr/share/man/man3/CURLOPT_KRBLEVEL.3
/usr/share/man/man3/CURLOPT_LOCALPORT.3
/usr/share/man/man3/CURLOPT_LOCALPORTRANGE.3
/usr/share/man/man3/CURLOPT_LOGIN_OPTIONS.3
/usr/share/man/man3/CURLOPT_LOW_SPEED_LIMIT.3
/usr/share/man/man3/CURLOPT_LOW_SPEED_TIME.3
/usr/share/man/man3/CURLOPT_MAIL_AUTH.3
/usr/share/man/man3/CURLOPT_MAIL_FROM.3
/usr/share/man/man3/CURLOPT_MAIL_RCPT.3
/usr/share/man/man3/CURLOPT_MAIL_RCPT_ALLLOWFAILS.3
/usr/share/man/man3/CURLOPT_MAXAGE_CONN.3
/usr/share/man/man3/CURLOPT_MAXCONNECTS.3
/usr/share/man/man3/CURLOPT_MAXFILESIZE.3
/usr/share/man/man3/CURLOPT_MAXFILESIZE_LARGE.3
/usr/share/man/man3/CURLOPT_MAXREDIRS.3
/usr/share/man/man3/CURLOPT_MAX_RECV_SPEED_LARGE.3
/usr/share/man/man3/CURLOPT_MAX_SEND_SPEED_LARGE.3
/usr/share/man/man3/CURLOPT_MIMEPOST.3
/usr/share/man/man3/CURLOPT_NETRC.3
/usr/share/man/man3/CURLOPT_NETRC_FILE.3
/usr/share/man/man3/CURLOPT_NEW_DIRECTORY_PERMS.3
/usr/share/man/man3/CURLOPT_NEW_FILE_PERMS.3
/usr/share/man/man3/CURLOPT_NOBODY.3
/usr/share/man/man3/CURLOPT_NOPROGRESS.3
/usr/share/man/man3/CURLOPT_NOPROXY.3
/usr/share/man/man3/CURLOPT_NOSIGNAL.3
/usr/share/man/man3/CURLOPT_OPENSOCKETDATA.3
/usr/share/man/man3/CURLOPT_OPENSOCKETFUNCTION.3
/usr/share/man/man3/CURLOPT_PASSWORD.3
/usr/share/man/man3/CURLOPT_PATH_AS_IS.3
/usr/share/man/man3/CURLOPT_PINNEDPUBLICKEY.3
/usr/share/man/man3/CURLOPT_PIPEWAIT.3
/usr/share/man/man3/CURLOPT_PORT.3
/usr/share/man/man3/CURLOPT_POST.3
/usr/share/man/man3/CURLOPT_POSTFIELDS.3
/usr/share/man/man3/CURLOPT_POSTFIELDSIZE.3
/usr/share/man/man3/CURLOPT_POSTFIELDSIZE_LARGE.3
/usr/share/man/man3/CURLOPT_POSTQUOTE.3
/usr/share/man/man3/CURLOPT_POSTREDIR.3
/usr/share/man/man3/CURLOPT_PREQUOTE.3
/usr/share/man/man3/CURLOPT_PRE_PROXY.3
/usr/share/man/man3/CURLOPT_PRIVATE.3
/usr/share/man/man3/CURLOPT_PROGRESSDATA.3
/usr/share/man/man3/CURLOPT_PROGRESSFUNCTION.3
/usr/share/man/man3/CURLOPT_PROTOCOLS.3
/usr/share/man/man3/CURLOPT_PROXY.3
/usr/share/man/man3/CURLOPT_PROXYAUTH.3
/usr/share/man/man3/CURLOPT_PROXYHEADER.3
/usr/share/man/man3/CURLOPT_PROXYPASSWORD.3
/usr/share/man/man3/CURLOPT_PROXYPORT.3
/usr/share/man/man3/CURLOPT_PROXYTYPE.3
/usr/share/man/man3/CURLOPT_PROXYUSERNAME.3
/usr/share/man/man3/CURLOPT_PROXYUSERPWD.3
/usr/share/man/man3/CURLOPT_PROXY_CAINFO.3
/usr/share/man/man3/CURLOPT_PROXY_CAINFO_BLOB.3
/usr/share/man/man3/CURLOPT_PROXY_CAPATH.3
/usr/share/man/man3/CURLOPT_PROXY_CRLFILE.3
/usr/share/man/man3/CURLOPT_PROXY_ISSUERCERT.3
/usr/share/man/man3/CURLOPT_PROXY_ISSUERCERT_BLOB.3
/usr/share/man/man3/CURLOPT_PROXY_KEYPASSWD.3
/usr/share/man/man3/CURLOPT_PROXY_PINNEDPUBLICKEY.3
/usr/share/man/man3/CURLOPT_PROXY_SERVICE_NAME.3
/usr/share/man/man3/CURLOPT_PROXY_SSLCERT.3
/usr/share/man/man3/CURLOPT_PROXY_SSLCERTTYPE.3
/usr/share/man/man3/CURLOPT_PROXY_SSLCERT_BLOB.3
/usr/share/man/man3/CURLOPT_PROXY_SSLKEY.3
/usr/share/man/man3/CURLOPT_PROXY_SSLKEYTYPE.3
/usr/share/man/man3/CURLOPT_PROXY_SSLKEY_BLOB.3
/usr/share/man/man3/CURLOPT_PROXY_SSLVERSION.3
/usr/share/man/man3/CURLOPT_PROXY_SSL_CIPHER_LIST.3
/usr/share/man/man3/CURLOPT_PROXY_SSL_OPTIONS.3
/usr/share/man/man3/CURLOPT_PROXY_SSL_VERIFYHOST.3
/usr/share/man/man3/CURLOPT_PROXY_SSL_VERIFYPEER.3
/usr/share/man/man3/CURLOPT_PROXY_TLS13_CIPHERS.3
/usr/share/man/man3/CURLOPT_PROXY_TLSAUTH_PASSWORD.3
/usr/share/man/man3/CURLOPT_PROXY_TLSAUTH_TYPE.3
/usr/share/man/man3/CURLOPT_PROXY_TLSAUTH_USERNAME.3
/usr/share/man/man3/CURLOPT_PROXY_TRANSFER_MODE.3
/usr/share/man/man3/CURLOPT_PUT.3
/usr/share/man/man3/CURLOPT_QUOTE.3
/usr/share/man/man3/CURLOPT_RANDOM_FILE.3
/usr/share/man/man3/CURLOPT_RANGE.3
/usr/share/man/man3/CURLOPT_READDATA.3
/usr/share/man/man3/CURLOPT_READFUNCTION.3
/usr/share/man/man3/CURLOPT_REDIR_PROTOCOLS.3
/usr/share/man/man3/CURLOPT_REFERER.3
/usr/share/man/man3/CURLOPT_REQUEST_TARGET.3
/usr/share/man/man3/CURLOPT_RESOLVE.3
/usr/share/man/man3/CURLOPT_RESOLVER_START_DATA.3
/usr/share/man/man3/CURLOPT_RESOLVER_START_FUNCTION.3
/usr/share/man/man3/CURLOPT_RESUME_FROM.3
/usr/share/man/man3/CURLOPT_RESUME_FROM_LARGE.3
/usr/share/man/man3/CURLOPT_RTSP_CLIENT_CSEQ.3
/usr/share/man/man3/CURLOPT_RTSP_REQUEST.3
/usr/share/man/man3/CURLOPT_RTSP_SERVER_CSEQ.3
/usr/share/man/man3/CURLOPT_RTSP_SESSION_ID.3
/usr/share/man/man3/CURLOPT_RTSP_STREAM_URI.3
/usr/share/man/man3/CURLOPT_RTSP_TRANSPORT.3
/usr/share/man/man3/CURLOPT_SASL_AUTHZID.3
/usr/share/man/man3/CURLOPT_SASL_IR.3
/usr/share/man/man3/CURLOPT_SEEKDATA.3
/usr/share/man/man3/CURLOPT_SEEKFUNCTION.3
/usr/share/man/man3/CURLOPT_SERVICE_NAME.3
/usr/share/man/man3/CURLOPT_SHARE.3
/usr/share/man/man3/CURLOPT_SOCKOPTDATA.3
/usr/share/man/man3/CURLOPT_SOCKOPTFUNCTION.3
/usr/share/man/man3/CURLOPT_SOCKS5_AUTH.3
/usr/share/man/man3/CURLOPT_SOCKS5_GSSAPI_NEC.3
/usr/share/man/man3/CURLOPT_SOCKS5_GSSAPI_SERVICE.3
/usr/share/man/man3/CURLOPT_SSH_AUTH_TYPES.3
/usr/share/man/man3/CURLOPT_SSH_COMPRESSION.3
/usr/share/man/man3/CURLOPT_SSH_HOST_PUBLIC_KEY_MD5.3
/usr/share/man/man3/CURLOPT_SSH_KEYDATA.3
/usr/share/man/man3/CURLOPT_SSH_KEYFUNCTION.3
/usr/share/man/man3/CURLOPT_SSH_KNOWNHOSTS.3
/usr/share/man/man3/CURLOPT_SSH_PRIVATE_KEYFILE.3
/usr/share/man/man3/CURLOPT_SSH_PUBLIC_KEYFILE.3
/usr/share/man/man3/CURLOPT_SSLCERT.3
/usr/share/man/man3/CURLOPT_SSLCERTTYPE.3
/usr/share/man/man3/CURLOPT_SSLCERT_BLOB.3
/usr/share/man/man3/CURLOPT_SSLENGINE.3
/usr/share/man/man3/CURLOPT_SSLENGINE_DEFAULT.3
/usr/share/man/man3/CURLOPT_SSLKEY.3
/usr/share/man/man3/CURLOPT_SSLKEYTYPE.3
/usr/share/man/man3/CURLOPT_SSLKEY_BLOB.3
/usr/share/man/man3/CURLOPT_SSLVERSION.3
/usr/share/man/man3/CURLOPT_SSL_CIPHER_LIST.3
/usr/share/man/man3/CURLOPT_SSL_CTX_DATA.3
/usr/share/man/man3/CURLOPT_SSL_CTX_FUNCTION.3
/usr/share/man/man3/CURLOPT_SSL_EC_CURVES.3
/usr/share/man/man3/CURLOPT_SSL_ENABLE_ALPN.3
/usr/share/man/man3/CURLOPT_SSL_ENABLE_NPN.3
/usr/share/man/man3/CURLOPT_SSL_FALSESTART.3
/usr/share/man/man3/CURLOPT_SSL_OPTIONS.3
/usr/share/man/man3/CURLOPT_SSL_SESSIONID_CACHE.3
/usr/share/man/man3/CURLOPT_SSL_VERIFYHOST.3
/usr/share/man/man3/CURLOPT_SSL_VERIFYPEER.3
/usr/share/man/man3/CURLOPT_SSL_VERIFYSTATUS.3
/usr/share/man/man3/CURLOPT_STDERR.3
/usr/share/man/man3/CURLOPT_STREAM_DEPENDS.3
/usr/share/man/man3/CURLOPT_STREAM_DEPENDS_E.3
/usr/share/man/man3/CURLOPT_STREAM_WEIGHT.3
/usr/share/man/man3/CURLOPT_SUPPRESS_CONNECT_HEADERS.3
/usr/share/man/man3/CURLOPT_TCP_FASTOPEN.3
/usr/share/man/man3/CURLOPT_TCP_KEEPALIVE.3
/usr/share/man/man3/CURLOPT_TCP_KEEPIDLE.3
/usr/share/man/man3/CURLOPT_TCP_KEEPINTVL.3
/usr/share/man/man3/CURLOPT_TCP_NODELAY.3
/usr/share/man/man3/CURLOPT_TELNETOPTIONS.3
/usr/share/man/man3/CURLOPT_TFTP_BLKSIZE.3
/usr/share/man/man3/CURLOPT_TFTP_NO_OPTIONS.3
/usr/share/man/man3/CURLOPT_TIMECONDITION.3
/usr/share/man/man3/CURLOPT_TIMEOUT.3
/usr/share/man/man3/CURLOPT_TIMEOUT_MS.3
/usr/share/man/man3/CURLOPT_TIMEVALUE.3
/usr/share/man/man3/CURLOPT_TIMEVALUE_LARGE.3
/usr/share/man/man3/CURLOPT_TLS13_CIPHERS.3
/usr/share/man/man3/CURLOPT_TLSAUTH_PASSWORD.3
/usr/share/man/man3/CURLOPT_TLSAUTH_TYPE.3
/usr/share/man/man3/CURLOPT_TLSAUTH_USERNAME.3
/usr/share/man/man3/CURLOPT_TRAILERDATA.3
/usr/share/man/man3/CURLOPT_TRAILERFUNCTION.3
/usr/share/man/man3/CURLOPT_TRANSFERTEXT.3
/usr/share/man/man3/CURLOPT_TRANSFER_ENCODING.3
/usr/share/man/man3/CURLOPT_UNIX_SOCKET_PATH.3
/usr/share/man/man3/CURLOPT_UNRESTRICTED_AUTH.3
/usr/share/man/man3/CURLOPT_UPKEEP_INTERVAL_MS.3
/usr/share/man/man3/CURLOPT_UPLOAD.3
/usr/share/man/man3/CURLOPT_UPLOAD_BUFFERSIZE.3
/usr/share/man/man3/CURLOPT_URL.3
/usr/share/man/man3/CURLOPT_USERAGENT.3
/usr/share/man/man3/CURLOPT_USERNAME.3
/usr/share/man/man3/CURLOPT_USERPWD.3
/usr/share/man/man3/CURLOPT_USE_SSL.3
/usr/share/man/man3/CURLOPT_VERBOSE.3
/usr/share/man/man3/CURLOPT_WILDCARDMATCH.3
/usr/share/man/man3/CURLOPT_WRITEDATA.3
/usr/share/man/man3/CURLOPT_WRITEFUNCTION.3
/usr/share/man/man3/CURLOPT_XFERINFODATA.3
/usr/share/man/man3/CURLOPT_XFERINFOFUNCTION.3
/usr/share/man/man3/CURLOPT_XOAUTH2_BEARER.3
/usr/share/man/man3/curl_easy_cleanup.3
/usr/share/man/man3/curl_easy_duphandle.3
/usr/share/man/man3/curl_easy_escape.3
/usr/share/man/man3/curl_easy_getinfo.3
/usr/share/man/man3/curl_easy_init.3
/usr/share/man/man3/curl_easy_option_by_id.3
/usr/share/man/man3/curl_easy_option_by_name.3
/usr/share/man/man3/curl_easy_option_next.3
/usr/share/man/man3/curl_easy_pause.3
/usr/share/man/man3/curl_easy_perform.3
/usr/share/man/man3/curl_easy_recv.3
/usr/share/man/man3/curl_easy_reset.3
/usr/share/man/man3/curl_easy_send.3
/usr/share/man/man3/curl_easy_setopt.3
/usr/share/man/man3/curl_easy_strerror.3
/usr/share/man/man3/curl_easy_unescape.3
/usr/share/man/man3/curl_easy_upkeep.3
/usr/share/man/man3/curl_escape.3
/usr/share/man/man3/curl_formadd.3
/usr/share/man/man3/curl_formfree.3
/usr/share/man/man3/curl_formget.3
/usr/share/man/man3/curl_free.3
/usr/share/man/man3/curl_getdate.3
/usr/share/man/man3/curl_getenv.3
/usr/share/man/man3/curl_global_cleanup.3
/usr/share/man/man3/curl_global_init.3
/usr/share/man/man3/curl_global_init_mem.3
/usr/share/man/man3/curl_global_sslset.3
/usr/share/man/man3/curl_mime_addpart.3
/usr/share/man/man3/curl_mime_data.3
/usr/share/man/man3/curl_mime_data_cb.3
/usr/share/man/man3/curl_mime_encoder.3
/usr/share/man/man3/curl_mime_filedata.3
/usr/share/man/man3/curl_mime_filename.3
/usr/share/man/man3/curl_mime_free.3
/usr/share/man/man3/curl_mime_headers.3
/usr/share/man/man3/curl_mime_init.3
/usr/share/man/man3/curl_mime_name.3
/usr/share/man/man3/curl_mime_subparts.3
/usr/share/man/man3/curl_mime_type.3
/usr/share/man/man3/curl_mprintf.3
/usr/share/man/man3/curl_multi_add_handle.3
/usr/share/man/man3/curl_multi_assign.3
/usr/share/man/man3/curl_multi_cleanup.3
/usr/share/man/man3/curl_multi_fdset.3
/usr/share/man/man3/curl_multi_info_read.3
/usr/share/man/man3/curl_multi_init.3
/usr/share/man/man3/curl_multi_perform.3
/usr/share/man/man3/curl_multi_poll.3
/usr/share/man/man3/curl_multi_remove_handle.3
/usr/share/man/man3/curl_multi_setopt.3
/usr/share/man/man3/curl_multi_socket.3
/usr/share/man/man3/curl_multi_socket_action.3
/usr/share/man/man3/curl_multi_socket_all.3
/usr/share/man/man3/curl_multi_strerror.3
/usr/share/man/man3/curl_multi_timeout.3
/usr/share/man/man3/curl_multi_wait.3
/usr/share/man/man3/curl_multi_wakeup.3
/usr/share/man/man3/curl_share_cleanup.3
/usr/share/man/man3/curl_share_init.3
/usr/share/man/man3/curl_share_setopt.3
/usr/share/man/man3/curl_share_strerror.3
/usr/share/man/man3/curl_slist_append.3
/usr/share/man/man3/curl_slist_free_all.3
/usr/share/man/man3/curl_strequal.3
/usr/share/man/man3/curl_strnequal.3
/usr/share/man/man3/curl_unescape.3
/usr/share/man/man3/curl_url.3
/usr/share/man/man3/curl_url_cleanup.3
/usr/share/man/man3/curl_url_dup.3
/usr/share/man/man3/curl_url_get.3
/usr/share/man/man3/curl_url_set.3
/usr/share/man/man3/curl_version.3
/usr/share/man/man3/curl_version_info.3
/usr/share/man/man3/libcurl-easy.3
/usr/share/man/man3/libcurl-env.3
/usr/share/man/man3/libcurl-errors.3
/usr/share/man/man3/libcurl-multi.3
/usr/share/man/man3/libcurl-security.3
/usr/share/man/man3/libcurl-share.3
/usr/share/man/man3/libcurl-symbols.3
/usr/share/man/man3/libcurl-thread.3
/usr/share/man/man3/libcurl-tutorial.3
/usr/share/man/man3/libcurl-url.3
/usr/share/man/man3/libcurl.3

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libcurl.a
